config/routes.rb
Rails.application.routes.draw do
  root 'web_forms#index'
  #get  '/web_forms/:title',to: 'web_forms#show'
  resources :web_forms
  resources :user_forms
  #get  '/web_forms',to: 'web_forms#index'
  
  #post '/web_forms',to: 'web_forms#create'
  #get  '/web_forms',to: 'web_forms#new'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_forms
    before_save { self.email = email.downcase }
    validates :username , presence: true, 
               uniqueness: {case_sensitive: false}, 
               length: { minimum: 3,maximum: 25 }
    VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email,presence: true,
               length: {maximum: 105},
               uniqueness: {case_sensitive: false},
               format:{with: VALID_EMAIL_REGEX}

end

app/models/user_form.rb
class UserForm < ApplicationRecord  
    belongs_to :web_form
    #validates :user_id, presence: true
    validates :web_form_id, presence: true
    validates :username, presence: true
    validates :phone_number, presence: true
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 3, maximum: 300}

    
end

app/models/web_form.rb
class WebForm < ApplicationRecord
    before_save do
        self.options.gsub!(/[\[\]\*]/,"") if attribute_present?("options")
    end
    extend FriendlyId
    friendly_id :title, use: :slugged

    def should_generate_new_friendly_id?
        title_changed? || super
    end
    
    has_many :user_forms
    mount_uploader :image,ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_forms_controller.rb
class UserFormsController < ApplicationController
    before_action :set_user_form, only: [:show, :edit, :update, :destroy]
  
    
    def index
      @user_forms = UserForm.all
    end
  
    
    def show
    end
  
    
    def new      
      @user_form = UserForm.new
    end
  
    def edit
    end
  
    
    def create
      #puts("web form idddddd ",params[:web])
      #puts params:title)
      #puts "here are all the params",params.inspect
      params.each do |key,value|
        puts "henaaaa #{key} is #{value}"
      end
      puts "hena el title",params[:user_form][:title]
      @web_form = WebForm.find_by(title: params[:user_form][:title])
      #@web_form = WebForm.find(1)
      puts("here is the description ",@web_form.description)
      puts "here is the user from params",user_form_params[:username]
      #@user_form = UserForm.new(user_form_params)
      @user_form = UserForm.new
      @user_form.username = user_form_params[:username]
      @user_form.phone_number = user_form_params[:phone_number]
      @user_form.web_form_id = @web_form.id
      @user_form.title = @web_form.title
      @user_form.description = @web_form.description
      puts "here is the id of the user form ",@user_form.web_form_id
      puts "el username",@user_form.username
      puts "user form ",@user_form
  
      respond_to do |format|
        if @user_form.save
          format.html { redirect_to @user_form, notice: 'User form was successfully created.' }
          format.json { render :show, status: :created, location: @user_form }
        else
          format.html { render :new }
          format.json { render json: @user_form.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @user_form.update(user_form_params)
          format.html { redirect_to @user_form, notice: 'User form was successfully updated.' }
          format.json { render :show, status: :ok, location: @user_form }
        else
          format.html { render :edit }
          format.json { render json: @user_form.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /web_forms/1
    # DELETE /web_forms/1.json
    def destroy
      @user_form.destroy
      respond_to do |format|
        format.html { redirect_to web_forms_url, notice: 'User form was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user_form
        #@user_form = UserForm.friendly.find(params[:id])
        @user_form = UserForm.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def user_form_params
        params.require(:user_form).permit(:title, :description, :image, :username,
         :phone_number, :email, :property_type, :job_title, :time_to_call, :web_form_id)#, :slug)
      end
  end
  

app/controllers/web_forms_controller.rb
class WebFormsController < ApplicationController
  before_action :set_web_form, only: [:show, :edit, :update, :destroy]

  # GET /web_forms
  # GET /web_forms.json
  def index
    @web_forms = WebForm.all
  end

  # GET /web_forms/1
  # GET /web_forms/1.json
  def show
  end

  # GET /web_forms/new
  def new
    @web_form = WebForm.new
  end

  # GET /web_forms/1/edit
  def edit
  end

  # POST /web_forms
  # POST /web_forms.json
  def create
    @web_form = WebForm.new(web_form_params)

    respond_to do |format|
      if @web_form.save
        format.html { redirect_to @web_form, notice: 'Web form was successfully created.' }
        format.json { render :show, status: :created, location: @web_form }
      else
        format.html { render :new }
        format.json { render json: @web_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /web_forms/1
  # PATCH/PUT /web_forms/1.json
  def update
    respond_to do |format|
      if @web_form.update(web_form_params)
        format.html { redirect_to @web_form, notice: 'Web form was successfully updated.' }
        format.json { render :show, status: :ok, location: @web_form }
      else
        format.html { render :edit }
        format.json { render json: @web_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /web_forms/1
  # DELETE /web_forms/1.json
  def destroy
    @web_form.destroy
    respond_to do |format|
      format.html { redirect_to web_forms_url, notice: 'Web form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_web_form
      @web_form = WebForm.friendly.find(params[:id])
      #@web_form = WebForm.where(title: params[:title] )
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def web_form_params
      params.require(:web_form).permit(:title, :description, :image, :slug, options:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_forms_helper.rb
module WebFormsHelper
    def checked(text)
        @web_form.options.nil? ? false : @web_form.options.match(text)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/user_forms/_form.html.erb
<%= form_with(model: user_form, local: true) do |form| %>
    <% if user_form.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user_form.errors.count, "error") %> prohibited this user_form from being saved:</h2>
  
        <ul>
          <% user_form.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :HeadLine %>
      <%= form.text_field :title %>
    </div>    
    <div class="field">
      <%= form.label :Name %>
      <%= form.text_field :username %>
    </div> 
    <div class="field">
      <%= form.label :Phone %>
      <%= form.text_field :phone_number %>
    </div> 
  
    <div class="actions" >
    
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/user_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Forms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_forms.each do |user_form| %>
      <tr>
        <td><%= user_form.title %></td>
        <td><%= user_form.description %></td>
        <td><%= link_to 'Show', user_form %></td>
        <td><%= link_to 'Edit', edit_user_form_path(user_form) %></td>
        <td><%= link_to 'Destroy', user_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Web Form', new_user_form_path %>

app/views/user_forms/new.html.erb
<h1>New User Form</h1>

<%= render 'form', user_form: @user_form %>

<%= link_to 'Back', user_forms_path %>

app/views/user_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Headline:</strong>
  <%= @user_form.title %>
</p>

<p>
  <strong>Layouts:</strong>
  <%= @user_form.description %>
</p>
<p>
  <strong>Name:</strong>
  <%= @user_form.username %>
</p>
<p>
  <strong>Phone number</strong>
  <%= @user_form.phone_number %>
</p>
<p>
  <strong>Email</strong>
  <%= @user_form.email %>
</p>
<p>
  <strong>Property type</strong>
  <%= @user_form.property_type %>
</p>




<%= link_to 'Edit', edit_user_form_path(@user_form) %> |
<%= link_to 'Back', user_forms_path %>

app/views/web_forms/_form.html.erb
<%= form_with(model: web_form, local: true) do |form| %>
  <% if web_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(web_form.errors.count, "error") %> prohibited this web_form from being saved:</h2>

      <ul>
        <% web_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :HeadLine %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :Layouts %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%=label_tag 'option_email', 'Email' %>
    <%= check_box_tag 'web_form[options][]','Email',checked('Email'),id:'option_email'%>

    <%=label_tag 'option_job_title', 'Job Title' %>
    <%= check_box_tag 'web_form[options][]','Job Title',checked('Job Title'),id:'option_job_title'%>

    <%=label_tag 'option_best_time_to_call', 'Best time to call'%>
    <%= check_box_tag 'web_form[options][]','Best time to call',checked('Best time to call'),id:'option_best_time_to_call'%>

    <%=label_tag 'option_property_type', 'Property type' %>
    <%= check_box_tag 'web_form[options][]','Property type',checked('Property type'),id:'option_property_type'%>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  

  <div class="actions" >
  
    <%= form.submit %>
  </div>
<% end %>

app/views/web_forms/edit.html.erb
<h1>Editing Web Form</h1>

<%= render 'form', web_form: @web_form %>

<%= link_to 'Show', @web_form %> |
<%= link_to 'Back', web_forms_path %>

app/views/web_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Web Forms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @web_forms.each do |web_form| %>
      <tr>
        <td><%= web_form.title %></td>
        <td><%= web_form.description %></td>
        <td><%= web_form.image %></td>
        <td><%= link_to 'Show', web_form %></td>
        <td><%= link_to 'Edit', edit_web_form_path(web_form) %></td>
        <td><%= link_to 'Destroy', web_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Web Form', new_web_form_path %>

app/views/web_forms/new.html.erb
<h1>New Web Form</h1>

<%= render 'form', web_form: @web_form %>

<%= link_to 'Back', web_forms_path %>

app/views/web_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Headline:</strong>
  <%= @web_form.title %>
</p>

<p>
  <strong>Layouts:</strong>
  <%= @web_form.description %>
</p>

<p>
  <strong>Image:</strong>
  <img src = "<%=@web_form.image%>">
  <%= @web_form.image %>
</p>
<p>
  <strong>Optional fields:</strong>
  <%= @web_form.options %>
</p>
<p>
  <strong>Mandatory fields:</strong>
</p>
<p>Name</p>
<p>Phone</p>


<%= link_to 'Edit', edit_web_form_path(@web_form) %> |
<%= link_to 'Back', web_forms_path %>